# Generated by Django 3.1.5 on 2021-01-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giris', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='satıs',
            name='adres',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='satıs',
            name='fiyat',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='satıs',
            name='marka',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='satıs',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='satıs',
            name='tel',
            field=models.CharField(max_length=20),
        ),
    ]
